fieldLayouts:
  3ca77279-91ca-4ed2-a806-6fc0e49af1ed:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d6333b08-9574-4a47-9ebf-e9dd61db5742
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7b6cb827-6ed5-400f-af34-3e5a5bdfac67 # Assets Field
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fdf18af8-e354-4052-a949-a241001cfbb1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5c7a8525-3882-4d34-91ab-89abbdc07046 # Category Field
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44603377-dc32-48ee-ab8c-9c47a56e55b5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eabe62dd-b801-42c9-955a-8ee090206b50 # Color Field
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 523a6312-c353-412f-99a0-592dfa74f3b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8aa25d25-894f-46dc-90ec-4321e430ed65 # Date Field
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 797f52e8-149d-41e1-a6f2-8fca0e65a4d7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ccc0d7c5-9563-4aa5-a5ac-7e9bfe333647 # Dropdown Field
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46e1db7a-27a5-4b7d-87ba-85eb7ec837d6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 73001bfc-68e5-4059-acf2-4ff4dba34359 # Entries Field
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c9736bd-9efe-46b4-8453-7336fa3604b7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 71730b1a-49d4-4e53-8f27-408897679aeb # Matrix Field
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 045220fa-680a-4667-8a9c-5b1c0940e9f6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 954225e6-b357-4830-8024-1c9f8ba04ec6 # Plain Text Field
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a05375b5-efe8-48d3-804b-09b23b58761c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2baff1e2-99ae-4d30-965d-b6028b684dff
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 8a2fe4b1-2b76-4ab7-90fa-1ee6d7121033 # Posts
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
