name: Doc Generation

on:
  push:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer require "craftcms/cms" --prefer-dist --no-progress

      - name: Generate docs
        run: php src/bin/generate-docs.php src/behaviors/TestableResponseBehavior.php docs/testable-responses.md

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          author_email: docbot@markhuot.com
          author_name: docbot
          message: GitHub action updating docs
