name: PHP Composer

on:
  push:

permissions:
  contents: read

env:
  project_config_version: 3.7

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CRAFT_APP_ID: pest
      CRAFT_ENVIRONMENT: dev
      CRAFT_SECURITY_KEY: asdy8f7tgaysdfas987gduyvfas87dfghui
      CRAFT_DB_DRIVER: mysql
      CRAFT_DB_SERVER: 127.0.0.1
      CRAFT_DB_PORT: 3306
      CRAFT_DB_DATABASE: pest
      CRAFT_DB_USER: root
      CRAFT_DB_PASSWORD: root
      CRAFT_DB_TABLE_PREFIX: craft_
      CRAFT_TEMPLATES_PATH: ./tests/templates

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: pest
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        craftVersion: ["^${{ env.project_config_version }}", "^4.2"]

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer require craftcms/cms:${{ env.project_config_version }} --prefer-dist --no-progress

    - name: Copy config files
      run: mkdir -p ./storage && cp -r ./stubs/config ./config

    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyse src

    - name: Install Craft
      run: ./src/bin/craft install --username=michael@bluth.com --email=michael@bluth.com --password=secret --siteName=Pest --siteUrl=http://localhost:8080 --language=en-US

    - name: Update to Craft ${{ matrix.craftVersion }}
      run: composer update "craftcms/cms:${{ matrix.craftVersion }}" -W && ./src/bin/craft migrate/all --no-backup=1 --interactive=0
      if: ${{ matrix.craftVersion != env.project_config_version }}

    - name: Run test suite
      run: ./vendor/bin/pest
